FROM alpine AS download
ARG CODER_VERSION=2.1.5
WORKDIR /tmp
RUN wget https://github.com/coder/coder/releases/download/v${CODER_VERSION}/coder_${CODER_VERSION}_linux_amd64.tar.gz
RUN tar xvf coder_${CODER_VERSION}_linux_amd64.tar.gz

FROM smartcommunitylab/digitalhub-dashboard
COPY passwd /etc/passwd
COPY --chmod=777 --from=download /tmp/coder /bin/coder
ENTRYPOINT ["/bin/dash","-c","exec /bin/coder agent"]
